# Netlify proxy to AWS Elastic Beanstalk (temporarily disabled)
# Uncomment to route /api to EB when needed.

# [[redirects]]
# from = "/api/*"
# to = "https://ai-powered-backend-env-2.eba-ybwywm7t.ap-southeast-1.elasticbeanstalk.com/api/:splat"
# status = 200
# force = true


