branch-defaults:
  main:
    environment: ai-powered-backend-env
    group_suffix: null
global:
  application_name: AI-Powered-Idea-Management
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
